"""Substrate gate for v0.2 — may THIS machine lawfully run v0.2's body?

Same law as v0.1's gate (body/verify_substrate.py), same reason: chaos amplifies
one ULP into a different creature, so the criterion is exact equality of a
full-trajectory hash. No tolerance. A machine that fails may never hold a lease.

WHY v0.1's GATE DOES NOT COVER v0.2. v0.1's trajectory is tau/ell/phi. v0.2 adds
the slow state `s`, and `s` is not a passenger -- it parameterises the fold
through B(s, wing), so a machine that computes tanh() or the leaky decay one ULP
differently produces a different creature even if its tau/ell arithmetic is
perfect. The gate must therefore hash what v0.2 actually is.

The scenario is SYNTHETIC and frozen (fixed literals below). It is never v0.2's
real state, and no real private phase appears here or in any CI log. Changing
any literal voids the reference.

TWO VERDICTS, matching what each one gates:
  dynamics_gate (HARD)   tau/ell/s trajectory hash over N_TICKS. Gates commits
                         to the seat. FAIL = this machine may never hold a lease.
  readout_gate  (SPEECH) the published readout every READOUT_EVERY ticks. Gates
                         quoting readouts in speech or biography. A machine may
                         legitimately pass the first and fail this one; then it
                         may live the creature but not speak for it.

  python3 verify_substrate_v02.py --make-reference   # certified substrate only
  python3 verify_substrate_v02.py                    # exit 0 PASS / 1 FAIL
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
V02 = HERE.parent
sys.path.insert(0, str(V02))
sys.path.insert(0, str(V02.parent / "maturity" / "harness"))

import numpy as np  # noqa: E402
import torch  # noqa: E402

# Pinning here is NOT enough, and the first reference generated by this file was
# written with 8 threads because of it: `compat` imports `lab_common`, which does
# torch.set_num_threads(DM_THREADS, default 14) at import time and silently
# overrides whatever the gate asked for. The pin is therefore re-applied after
# the model is loaded and ASSERTED before the run -- an unasserted pin is just a
# comment. (v0.1's study found thread count didn't change its results; that is a
# finding about v0.1's dynamics, not a licence to leave the knob unpinned in a
# hash that defines who may hold a lease.)
torch.set_num_threads(1)
THREADS = 1

import genome_v02 as G  # noqa: E402
from state_io import dump_state, fingerprint, load_state  # noqa: E402

REF_F = HERE / "substrate_reference_v02.json"

# ---- canonical synthetic scenario (frozen; changing any literal voids the reference)
SEED = 11
WARM = 300
N_TICKS = 5000
READOUT_EVERY = 100
# two inputs, delivered at fixed ticks, so the gate exercises `hear` -> `pending`
# -> `s` -> B(s) -> the fold, which is the whole v0.2 causal chain. A gate that
# only ticks an undisturbed creature would not test the part that is new.
INPUTS = ((600, [0.9, -0.6]), (2400, [-1.1, 0.35]))
INPUT_WINDOW = 120


def cpu_model() -> str:
    try:
        for line in Path("/proc/cpuinfo").read_text().splitlines():
            if line.startswith("model name"):
                return line.split(":", 1)[1].strip()
    except Exception:                       # noqa: BLE001
        pass
    return platform.processor() or "unknown"


def canonical_run() -> dict:
    t0 = time.time()
    import compat
    cfg, gcfg, _ = compat.shared_context()
    model = compat.load_model(cfg, gcfg)
    torch.set_num_threads(THREADS)          # re-pin: lab_common moved it at import
    assert torch.get_num_threads() == THREADS, (
        f"substrate not pinned: {torch.get_num_threads()} threads")

    e = G.V02Engine(model, SEED, warm=WARM)
    sched = dict(INPUTS)

    h_dyn = hashlib.sha256()
    h_out = hashlib.sha256()
    with torch.no_grad():
        for t in range(N_TICKS):
            if t in sched:
                e.hear(np.array(sched[t], float), window=INPUT_WINDOW)
            e._tick()
            h_dyn.update(e.tau.numpy().tobytes())
            h_dyn.update(e.ell.numpy().tobytes())
            h_dyn.update(np.asarray(e.s, dtype=np.float64).tobytes())
            h_dyn.update(np.float64(e.wing_ema).tobytes())
            if (t + 1) % READOUT_EVERY == 0:
                h_out.update(json.dumps(e.observe(), sort_keys=True).encode())

    return dict(
        n_ticks=N_TICKS, warm=WARM, seed=SEED, readout_every=READOUT_EVERY,
        inputs=[[k, v] for k, v in INPUTS], input_window=INPUT_WINDOW,
        genome=dict(TAU_MEM=G.TAU_MEM, KAPPA_B=G.KAPPA_B, KAPPA_A=G.KAPPA_A,
                    S_CLIP=G.S_CLIP, WING_W=G.WING_W, DIM_S=G.DIM_S),
        dynamics_sha256=h_dyn.hexdigest(),
        readout_sha256=h_out.hexdigest(),
        final_fingerprint=fingerprint(e),
        blob_sha256=hashlib.sha256(dump_state(e).encode()).hexdigest(),
        platform=dict(
            python=platform.python_version(), torch=torch.__version__,
            numpy=np.__version__, torch_threads=torch.get_num_threads(),
            cpu=cpu_model(), machine=platform.machine(),
            aten_cpu_capability=os.environ.get("ATEN_CPU_CAPABILITY", "<unset>"),
        ),
        elapsed_s=round(time.time() - t0, 2),
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--make-reference", action="store_true")
    ap.add_argument("--json-out", type=Path)
    args = ap.parse_args()

    res = canonical_run()
    print(json.dumps(res["platform"], indent=2))
    print(f"dynamics_sha256 = {res['dynamics_sha256']}")
    print(f"readout_sha256  = {res['readout_sha256']}   ({res['elapsed_s']}s)")
    if args.json_out:
        args.json_out.write_text(json.dumps(res, indent=1))

    if args.make_reference:
        REF_F.write_text(json.dumps(res, indent=1))
        print(f"reference written: {REF_F}")
        return 0

    if not REF_F.exists():
        print(f"NO REFERENCE at {REF_F} — run --make-reference on the certified "
              f"substrate first. Refusing to pass a gate with nothing to gate against.")
        return 1

    ref = json.loads(REF_F.read_text())
    if ref.get("genome") != res.get("genome"):
        print("GENOME MISMATCH — the reference was made from a different genome; "
              "this gate is void until a new reference is certified.")
        return 1

    gates = {
        "dynamics_gate": res["dynamics_sha256"] == ref["dynamics_sha256"],
        "readout_gate": res["readout_sha256"] == ref["readout_sha256"],
    }
    for name, ok in gates.items():
        print(f"{name:14s} {'PASS' if ok else 'FAIL'}")
    if not gates["dynamics_gate"]:
        # the useful diagnostic: WHERE it diverged, not just that it did
        for k in ("tau", "ell", "s", "wing_ema", "n"):
            a, b = res["final_fingerprint"][k], ref["final_fingerprint"][k]
            if a != b:
                print(f"  final {k} differs:\n    here {a}\n    ref  {b}")
    print(f"\nVERDICT: this machine may {'HOLD A LEASE' if gates['dynamics_gate'] else 'NOT hold a lease'}"
          f"; readouts {'may' if gates['readout_gate'] else 'may NOT'} be quoted.")
    return 0 if gates["dynamics_gate"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
