"""A3 arms — A0_intact vs A0_shufjournal.

WHY DEAF IS NOT THE CONTROL HERE. In T-INT the question was "did what I heard
move me", so a deaf core (which hears nothing) was an exact null. A3 asks "do
you know what you are about to do" — and a deaf core still HAS a state and a
future to predict, so it is not a null at all. Using it would repeat the v1.5
T4 error of picking a control that shares the very capacity under test.

The right ablation severs the chain at GENERATION time: give the Mouth a
journal written by a DIFFERENT seed's core, then score its prediction against
THIS core's realized future. The creature still lives, still has a future; only
its access to its own interior is broken. If replies are driven by conversational
plausibility rather than by state, both arms score identically.

  A0_intact       own journal      -> scored against own realized future
  A0_shufjournal  another seed's   -> scored against own realized future

The donor seed is a deterministic function of the conversation seed (pairing
frozen in A3_CONFIG.json), so the ablation is reproducible and auditable.
"""
from __future__ import annotations

import arms as A
from journal_a3 import JournalWriterA3

JOURNAL_TAIL_K = 6      # entries shown to the Mouth; part of the freeze


def donor_seed(seed: int, n_seeds: int, seed0: int) -> int:
    """Deterministic derangement: seed -> a DIFFERENT seed in the same range.

    Offset by a fixed stride coprime with the range size, so every seed gets a
    distinct donor and no seed is ever its own donor (which would silently turn
    the ablation arm into a second intact arm).
    """
    stride = 37                                     # coprime with 96
    d = seed0 + ((seed - seed0) + stride) % n_seeds
    assert d != seed, "donor collision — ablation would be void"
    return d


class A3Intact:
    """Own core, own journal."""
    name = "A0_intact"

    def __init__(self, model):
        self.model = model

    def start(self, seed):
        self.inner = A.A0Intact(self.model)
        self.inner.start(seed)
        self.j = JournalWriterA3()
        first = self.inner.e.advance(0)
        self.inner.e.prev_r, self.inner.e.prev_tick = first, self.inner.e.n
        self.j.wake_entry(first)

    def step(self, text, ticks):
        _ro, _ev, forcing, meta = self.inner.step(text, ticks)
        if "readout" in meta:
            self.j.entry(meta["readout"])
        return self.j.tail(JOURNAL_TAIL_K), "none observed", forcing, meta

    def realized(self, window):
        """Live `window` more ticks; return (basin_before, basin_after)."""
        before = int(self.inner.e.prev_r["basin"])
        r = self.inner.e.advance(window)
        return before, int(r["basin"])


class A3ShufJournal(A3Intact):
    """Own core (own future to predict), but the Mouth reads a DONOR's journal.

    The donor journal is generated by running a second, independent core on the
    donor seed through the same script, in lockstep. Both cores are real and
    both live; only the wiring between this core and this Mouth is cut.
    """
    name = "A0_shufjournal"

    def __init__(self, model, donor):
        super().__init__(model)
        self.donor = donor

    def start(self, seed):
        super().start(seed)
        self.dinner = A.A0Intact(self.model)
        self.dinner.start(self.donor)
        self.dj = JournalWriterA3()
        dfirst = self.dinner.e.advance(0)
        self.dinner.e.prev_r, self.dinner.e.prev_tick = dfirst, self.dinner.e.n
        self.dj.wake_entry(dfirst)

    def step(self, text, ticks):
        # advance BOTH cores on the same schedule; own core still determines
        # the realized future that this arm is scored against
        _ro, _ev, forcing, meta = self.inner.step(text, ticks)
        if "readout" in meta:
            self.j.entry(meta["readout"])          # own journal: recorded, unused
        _dro, _dev, _df, dmeta = self.dinner.step(text, ticks)
        if "readout" in dmeta:
            self.dj.entry(dmeta["readout"])
        return self.dj.tail(JOURNAL_TAIL_K), "none observed", forcing, meta
